spring.application.name=06_SpringBoot_FirstApplication
spring.banner.location=classpath:banner.txt
spring.main.banner-mode=console

#Configuring the employee bean data
emplId=123
empName=Mahesh
salary=50000
designation=Software Engineer

