spring.application.name=09_SpringDataJpa_FirstApplication

#MySql database configuration
#MySQL Database Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/95_springbootms_db
spring.datasource.username=root
spring.datasource.password=root

#jpa configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update