#Bulk Values injection configuration
#userdefined keys
#com.ashokit.id=12345
#com.ashokit.name=Mahesh1
#com.ashokit.salary=52000

#Object property keys
#com.ashokit.address.doorNo=12-22-32
#com.ashokit.address.streetName=Ameerpet1
#com.ashokit.address.cityName=Hyderabad

#supplying the Array of Values i.e,Index based Injection
#com.ashokit.colors[0]=Yellow
#com.ashokit.colors[1]=Red
#com.ashokit.colors[2]=Green
#com.ashokit.colors[3]=Blue

#supplying the array of valuesi.e.,Inline value based injection
#com.ashokit.colors=black,Yellow,Green,Blue,Orange