spring.application.name=15_SpringBootMVC_FormSubmit_App

#configure the prefix,suffix of view resolver
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

server.port=9090

#oracle database configuration
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=manager

#jpa configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update