spring.application.name=09_SpringDataJpa_FirstApplication

#oracle database configuration
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=system
spring.datasource.password=manager

#jpa configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update
#JpaRepoistory configuration
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true